[0m14:55:30.659536 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d69367c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d5d280a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d61df040>]}


============================== 14:55:30.665712 | 469bd108-b30d-4f37-b5ac-4676b9f81917 ==============================
[0m14:55:30.665712 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m14:55:30.666608 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/amit/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:55:30.689029 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse logging event dictionary. Failed to parse dir field: expected string or bytes-like object.. Dictionary: {'dir': PosixPath('/home/amit/.dbt')}
[0m14:55:30.690776 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:55:58.207778 [debug] [MainThread]: Starter project path: /home/amit/.local/lib/python3.8/site-packages/dbt/include/starter_project
[0m14:55:58.361317 [info ] [MainThread]: 
Your new dbt project "custom_postgres" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:55:58.362058 [info ] [MainThread]: Setting up your profile.
[0m15:02:09.435144 [error] [MainThread]: Encountered an error:

[0m15:02:09.451076 [error] [MainThread]: Traceback (most recent call last):
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 153, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/cli/requires.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/cli/main.py", line 477, in init
    results = task.run()
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/task/init.py", line 346, in run
    self.setup_profile(profile_name)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/task/init.py", line 262, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/task/init.py", line 179, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/task/init.py", line 163, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
  File "/home/amit/.local/lib/python3.8/site-packages/dbt/task/init.py", line 129, in generate_target_from_input
    target[key] = click.prompt(
  File "/home/amit/.local/lib/python3.8/site-packages/click/termui.py", line 166, in prompt
    value = prompt_func(prompt)
  File "/home/amit/.local/lib/python3.8/site-packages/click/termui.py", line 149, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m15:02:09.460309 [debug] [MainThread]: Resource report: {"command_name": "init", "command_wall_clock_time": 398.93222, "process_user_time": 1.531825, "process_kernel_time": 0.170202, "process_mem_max_rss": "85800", "process_in_blocks": "72752", "command_success": false, "process_out_blocks": "0"}
[0m15:02:09.461755 [debug] [MainThread]: Command `dbt init` failed at 15:02:09.461519 after 398.93 seconds
[0m15:02:09.462593 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d69367c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d420a430>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fe5d5a4c760>]}
[0m15:02:09.463519 [debug] [MainThread]: Flushing usage events
[0m15:02:10.275487 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:03:16.462320 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c211347c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c20fea040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c208fa040>]}


============================== 15:03:16.467728 | 6c88e602-0854-4d3d-bc7f-f3f70e254ec5 ==============================
[0m15:03:16.467728 [info ] [MainThread]: Running with dbt=1.9.0-b2
[0m15:03:16.468784 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/amit/.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m15:03:33.008725 [info ] [MainThread]: A project called custom_postgres already exists here.
[0m15:03:33.011185 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 16.641258, "process_user_time": 1.492677, "process_kernel_time": 0.140487, "process_mem_max_rss": "80900", "process_in_blocks": "39440", "process_out_blocks": "0"}
[0m15:03:33.012856 [debug] [MainThread]: Command `dbt init` succeeded at 15:03:33.012614 after 16.64 seconds
[0m15:03:33.014136 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c211347c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c2089c820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f5c208fa040>]}
[0m15:03:33.015493 [debug] [MainThread]: Flushing usage events
[0m15:03:33.781014 [debug] [MainThread]: An error was encountered while trying to flush usage events
